version: '3.8'
services:
  capsrv:
    #env_file: .env
    image: innovanon/capsrv
    container_name:  capsrv
    ports:
      - "0.0.0.0:43415:43415/tcp"
    volumes:
      - aircaps:/var/teamhack/caps:rw
      - airpsks:/var/teamhack/psks:ro
      #- syslog-client:/etc/rsyslog.d:ro
    #command: ["-w", "/var/teamhack/wordlists/$TEAMHACK_WORDLIST", "-b", $TEAMHACK_BSSID, "-l", "/var/teamhack/psks/$TEAMHACK_BSSID.psk", "/var/teamhack/caps/$TEAMHACK_BSSID.cap"]
    restart:         always
    #network_mode:    service:vpn-s1
    #healthcheck:
    ##  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    #  test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
    #  interval:     10s
    #  timeout:       3s
    #  retries:       10
    #depends_on:
    #  import_db:
    #    condition: service_started
    #  syslog:
    #    condition: service_started
    #    #condition:   service_healthy
    #networks:
    #  network:
    #    ipv4_address: 10.5.0.9

